@startuml

group 设备数据上行
autonumber "<b>[000]"
设备 --> 驱动中连接模块: 连接建立
驱动中连接模块 --> 编解码模块: 上传数据
编解码模块 --> 编解码模块:　解析数据
编解码模块 -> 驱动设备接入sdk: sdk封装数据上传
end

group 设备数据下行
autonumber "<b>[000]"
设备 <-- 驱动中连接模块: 下发数据到设备
驱动中连接模块 <-- 编解码模块: 下发数据
编解码模块 <-- 编解码模块:　编码数据
编解码模块 <-- 驱动设备接入sdk: sdk接收下行数据
end

@enduml